---
#- name: Make app directory
#  file: path=/tmp/ansible_test state=directory mode=0755

#- name: install releated packages for network tracking
#  package:
#    name: "{{ item }}"
#    state: present
#  with_items:
#    - tcpdump
#    - traceroute

- name: Set timezone to KST
  command: timedatectl set-timezone Asia/Seoul
  when: ansible_date_time.tz != 'KST'

- name: check NTP service
  shell : /usr/bin/timedatectl | grep "NTP service"
  ignore_errors: True
  changed_when: False
  register: result

- name: Set NTP service active
  command: /usr/bin/timedatectl set-ntp on
  when: result.stdout != "active"
